### ISSUE TITLE
Use $GITHUB_OUTPUT file to avoid deprecation warning

### ISSUE THREAD

**Issue by schlomo** [mdgreenwald/mozilla-sops-action#164]
Since https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ we get a warning in every action:
![image](https://user-images.githubusercontent.com/101384/210254025-b444a723-1b2f-4334-8dc4-c39e0c6818c1.png)

Can you please implement the new `$GITHUB_OUTPUT` file to set the outputs?

Thanks a lot!

**Comment by mdgreenwald** [comment]
@schlomo This has been fixed in v1.4.0. Thanks.

**Comment by mdgreenwald** [comment]
@schlomo I have now release v1.4.1 as well.
