### ISSUE TITLE
`latest` download fails due to file name changes in v3.8.0

### ISSUE THREAD

**Issue by Daveography** [mdgreenwald/mozilla-sops-action#195]
Using `latest` (the default) version now causes the task to fail due to a change in release file names as of [SOPS v3.8.0](https://github.com/getsops/sops/releases/tag/v3.8.0) released a couple of weeks ago.

```
Run mdgreenwald/mozilla-sops-action@v1
Object prototype may only be an Object or null: undefined
Waiting 19 seconds before trying again
Object prototype may only be an Object or null: undefined
Waiting 12 seconds before trying again
Error: Error: Failed to download Sops from location  https://github.com/mozilla/sops/releases/download/v3.8.0/sops-v3.8.0.linux
```

The new release files now append the platform to the name, e.g., `https://github.com/getsops/sops/releases/download/v3.8.0/sops-v3.8.0.linux.amd64`

Workaround is to specify version `3.7.3`.

**Comment by mdgreenwald** [comment]
I believe this was already fixed here:
https://github.com/mdgreenwald/mozilla-sops-action/pull/193/files
