### ISSUE TITLE
Upgrade from Node.js 16  to Node.js 20

### ISSUE THREAD

**Issue by rafalpietrawski** [mdgreenwald/mozilla-sops-action#207]
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: mdgreenwald/mozilla-sops-action@v1.5.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by mdgreenwald** [comment]
@fabn This should be fixed in [v1.6.0](https://github.com/mdgreenwald/mozilla-sops-action/releases/tag/v1.6.0).

**Comment by fabn** [comment]
Thanks 💪🏻

**Comment by mdgreenwald** [comment]
@fabn Sorry it took so long! I have been battling several illnesses and then went on a brief vacation. Glad I could help get this fixed for you. 👍🏻

**Comment by fabn** [comment]
Don't worry, I hope everything is ok now. Thanks again.
